removed comments
ivanms1/project-shelf-old pull request #104
Opened 2021-03-19 05:15 UTC by rohilpinto

2021-03-19 05:18 UTC, ivanms1 approved these changes
Great job :+1:

2021-03-19 05:18 UTC, Raj2631 approved these changes
Good work

2021-03-19 05:20 UTC, Raj2631 requested changes

2021-03-19 05:20 UTC, Raj2631 commented on client/src/pages/Register/Register.js
> +
add this console back again

2021-03-19 05:23 UTC, rohilpinto commented on client/src/pages/Register/Register.js
> +
Done

2021-03-19 05:24 UTC, Raj2631 approved these changes

2021-03-19 05:26 UTC, revengemiroz approved these changes

2021-03-19 15:43 UTC, rohilpinto commented
Changed Icons

2021-03-19 16:19 UTC, ivanms1 commented on client/src/components/Cardv2/style.js
> +      /* transform: translateY(25px) */
remove please

2021-03-19 16:19 UTC, ivanms1 commented on client/src/pages/Register/Register.js
> +        // console.log(consoled)
remove please

2021-03-23 05:19 UTC, rohilpinto commented on client/src/components/Cardv2/style.js
> +      /* transform: translateY(25px) */
done

2022-12-20 13:11 UTC, closed without merging