Fix/card design
ivanms1/project-shelf-old pull request #45
Opened 2021-02-04 19:24 UTC by revengemiroz

![image](https://user-images.githubusercontent.com/16122132/106944507-c2e79900-674e-11eb-909e-672925550937.png)

2021-02-06 13:23 UTC, ivanms1 commented on client/src/components/Cardv2/CardDetails/CardDetails.js
> +          <a onClick={() => history.push('/')}>Home</a> /{' '}
use <Link />

2021-02-06 13:24 UTC, ivanms1 commented on client/src/components/Cardv2/CardDetails/CardDetails.js
> -                  <img src={project.preview} />
add alt, listen to the linter, we don't need more warnings.

2021-02-06 13:25 UTC, ivanms1 commented on client/src/components/Cardv2/Cardtwo.js
> +                onClick={() => history.push(`/projectDetails/${project.id}`)}
wrap it on a Link

2021-02-06 13:26 UTC, ivanms1 commented on client/src/pages/Edit/Edit.js
> +      // setOpen((o) => !o);
remove

2021-02-06 13:26 UTC, ivanms1 commented on client/src/pages/Edit/Edit.js
> +      {/* <PopupModal open={open} closeOnDocumentClick={false} onClose={closeModal}>
why is this commented?
can it be removed?

2021-02-06 13:28 UTC, ivanms1 commented on client/src/pages/SubmitYourProject/Submit.js
> +        <Button addCSS={CustomYesButton} onClick={() => history.push('/')}>
you could a prop to the Button component to make it render as a Link

2021-02-06 13:28 UTC, ivanms1 requested changes
see comments

2021-02-06 16:16 UTC, revengemiroz commented on client/src/components/Cardv2/CardDetails/CardDetails.js
> -                  <img src={project.preview} />
done

2021-02-06 16:16 UTC, revengemiroz commented on client/src/components/Cardv2/CardDetails/CardDetails.js
> -                  <img src={project.preview} />
done

2021-02-06 16:20 UTC, revengemiroz commented on client/src/components/Cardv2/Cardtwo.js
> +                onClick={() => history.push(`/projectDetails/${project.id}`)}
done

2021-02-06 16:33 UTC, revengemiroz commented on client/src/components/Cardv2/CardDetails/CardDetails.js
> +          <a onClick={() => history.push('/')}>Home</a> /{' '}
Link ?

2021-02-06 16:36 UTC, revengemiroz commented on client/src/pages/Edit/Edit.js
> +      {/* <PopupModal open={open} closeOnDocumentClick={false} onClose={closeModal}>
for now its should be commented because i have replaced the popup Modal in this but since Edit page has a lot of issues and we need to make Edit page use components from Submit ill open a new PR for Edit page and solve all the issue related to it there. For now it can be uncommented.

2021-02-07 13:55 UTC, ivanms1 commented on client/src/components/Cardv2/CardDetails/CardDetails.js
> +          <a onClick={() => history.push('/')}>Home</a> /{' '}
yes

2021-02-07 14:01 UTC, ivanms1 approved these changes

2021-02-07 14:02 UTC, merged