Fix/bugs
ivanms1/project-shelf-old pull request #48
Opened 2021-02-10 11:00 UTC by revengemiroz

2021-02-13 18:50 UTC, revengemiroz commented on client/src/components/Header/Header.js
>            history.push('/signin');
since we have Redirect in privateRoute do we need to do histoy.push ?

2021-02-14 09:53 UTC, revengemiroz commented on client/src/components/Header/Header.js
> +          setIsAuthenticated(false);
since we have Redirect in privateRoute do we need to do histoy.push ?

2021-02-14 10:14 UTC, ivanms1 commented on client/src/components/Header/Header.js
> +          setIsAuthenticated(false);
can test and see if it's needed?
Changing `isAuthenticated` refreshes the whole app anyway.

2021-02-14 17:43 UTC, revengemiroz commented on client/src/components/Header/Header.js
> +          setIsAuthenticated(false);
yeah i tested it and it seems we dont need the history push

2021-02-15 00:07 UTC, ivanms1 commented on client/src/components/DropDown/DropDownApp.js
> +              ></DropdownItem>
<DropdownItem />

2021-02-15 00:11 UTC, ivanms1 commented on client/src/pages/Admin/Admin.js
> +    return console.log(error);
return jsx

2021-02-15 00:12 UTC, ivanms1 commented on client/src/pages/SignIn/Signin.js
>      console.log(error.message);
return jsx

2021-02-17 05:47 UTC, ivanms1 commented on client/src/pages/Activated/Activated.js
> +    return console.log(errorR);
return jsx please

2021-02-17 05:47 UTC, ivanms1 commented on client/src/pages/Activated/Activated.js
> +                  project.isApproved === true && (
```suggestion
                  project.isApproved && (
```

2021-02-17 05:49 UTC, ivanms1 commented on client/src/pages/NotActivated/Notactivated.js
> +    (project) => project.isApproved === false
```suggestion
    (project) => !project.isApproved
```

2021-02-17 05:50 UTC, ivanms1 commented on client/src/pages/SignIn/Signin.js
>  const GET_USER_QUERY = loader('./mutationLoginUser.graphql');
wrong name

2021-02-17 05:50 UTC, ivanms1 commented on client/src/pages/SubmitYourProject/SubmitForm.js
> +                  {console.log('Loading')}
remove

2021-02-17 05:52 UTC, ivanms1 requested changes
check comments

2021-02-17 07:16 UTC, ivanms1 approved these changes

2021-02-17 07:16 UTC, merged