Update/modals
ivanms1/project-shelf-old pull request #64
Opened 2021-02-16 18:21 UTC by revengemiroz

2021-03-06 13:58 UTC, ivanms1 commented on client/src/components/Button/style.js
> +      // case 'delete':
remove please

2021-03-06 13:59 UTC, ivanms1 commented on client/src/components/PopupModal/Modal.js
> +  onClick = () => {},
just make it null, and add an `if` before calling the function

2021-03-06 14:00 UTC, ivanms1 commented on client/src/components/PopupModal/Modal.js
> +const Modal_Messages = {
`modalMessages`

2021-03-06 14:00 UTC, ivanms1 commented on client/src/components/PopupModal/Modal.js
> +const Modal_Messages = {
or `MODAL_MESSAGES`

2021-03-06 14:01 UTC, ivanms1 commented on client/src/pages/SubmitYourProject/SubmissionModal/style.js
> +  font-family: 'Poppins';
I've seen this in other parts in the pr, wouldn't it be better to change the font in the root?

2021-03-06 14:03 UTC, ivanms1 commented
did you pass the svgs through svgo?
please solve the conflicts

2021-03-06 14:03 UTC, ivanms1 requested changes
check comments and update

2021-03-13 05:56 UTC, revengemiroz commented on client/src/components/Button/style.js
> +      // case 'delete':
done

2021-03-13 05:56 UTC, revengemiroz commented on client/src/components/PopupModal/Modal.js
> +  onClick = () => {},
done

2021-03-13 05:56 UTC, revengemiroz commented on client/src/components/PopupModal/Modal.js
> +const Modal_Messages = {
done

2021-03-13 05:57 UTC, revengemiroz commented on client/src/pages/SubmitYourProject/SubmissionModal/style.js
> +  font-family: 'Poppins';
that will be included in the next PR since we need to create a globabl styles and include majority of the styles including styled components

2021-03-19 23:16 UTC, ivanms1 commented on client/src/components/Cardv2/CardDetails/CardDetails.js
>          onClick={() => {
```suggestion
        onClick={() => deleteUserProject(project?.id)}
```

2021-03-19 23:17 UTC, ivanms1 approved these changes

2021-03-19 23:18 UTC, ivanms1 commented
just one small check, check comment

2021-04-05 04:22 UTC, closed without merging