Update/menu dropdown
ivanms1/project-shelf-old pull request #73
Opened 2021-02-20 11:06 UTC by revengemiroz

2021-02-23 14:20 UTC, ivanms1 commented on client/src/assets/cog.svg
> +<svg viewBox="0 0 512 512" height='28px' width='28px'><path d="M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.
you can't set this with styled components?

2021-02-23 14:21 UTC, ivanms1 commented on client/src/components/DropDown/DropDownPopper.js
> +  function handleDocumentClick(event) {
is this to detect the click outside?

2021-02-25 08:00 UTC, revengemiroz commented on client/src/components/DropDown/DropDownPopper.js
> +  function handleDocumentClick(event) {
yus

2021-02-25 08:02 UTC, revengemiroz commented on client/src/assets/cog.svg
> +<svg viewBox="0 0 512 512" height='28px' width='28px'><path d="M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.
we can but its messy to target the svg from the styled components. This svg was intended to be of small size but i was lazy and left it to be big.

2021-02-25 08:04 UTC, ivanms1 commented on client/src/components/DropDown/DropDownPopper.js
> +  function handleDocumentClick(event) {
make it reusable
https://usehooks.com/useOnClickOutside
or use a library

2021-02-25 08:05 UTC, ivanms1 commented on client/src/assets/cog.svg
> +<svg viewBox="0 0 512 512" height='28px' width='28px'><path d="M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.
don't be lazy :smile: 
if we ever need to use this svg again it would have to be this size.

2021-02-27 09:28 UTC, ivanms1 requested changes
check comments

2021-02-27 11:14 UTC, revengemiroz commented on client/src/components/DropDown/DropDownPopper.js
> +  function handleDocumentClick(event) {
done

2021-02-27 11:16 UTC, revengemiroz commented on client/src/assets/cog.svg
> +<svg viewBox="0 0 512 512" height='28px' width='28px'><path d="M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.
Reasons : ``
1. Used only once.
2. it was meant to be of size 28px instead of 350px i made a mistake while importing it as others are all 28px.
3. If this is changed to 350px. We need to wrap its parent around a div and put custom styles only for it
``

2021-02-27 14:02 UTC, ivanms1 commented on client/src/components/DropDown/style.js
> +export const MenuButton = styled.div`
this should be a button

2021-02-27 14:09 UTC, ivanms1 commented on client/src/components/DropDown/DropDownPopper.js
> +        <DropdownContainer style={styles.offset} visible={visible}>
```suggestion
        { visible && <DropdownContainer style={styles.offset}>
```

2021-02-27 14:13 UTC, revengemiroz commented on client/src/components/DropDown/style.js
> +export const MenuButton = styled.div`
done

2021-02-27 14:24 UTC, revengemiroz commented on client/src/components/DropDown/DropDownPopper.js
> +        <DropdownContainer style={styles.offset} visible={visible}>
done

2021-03-01 03:26 UTC, ivanms1 approved these changes

2021-03-01 03:26 UTC, merged